<Project Sdk="Microsoft.NET.Sdk.Razor">
  <ItemGroup>
    <ProjectReference Include="..\..\Alife\Alife.Framework\Alife.Framework.csproj" />
    <ProjectReference Include="..\Alife.Function.FunctionCaller\Alife.Function.FunctionCaller.csproj" />
    <ProjectReference Include="..\Alife.Function.MessageFilter\Alife.Function.MessageFilter.csproj" />
  </ItemGroup>
</Project>
